project:
  type: book
  output-dir: docs

book:
  title: "ExperimentalDesignAnalysisProjects"
  author: "Jane Doe"
  date: "1/3/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



